'use client';

import Script from 'next/script';
import Link from 'next/link';
import { useEffect, useRef, useState, useCallback } from 'react';
import { Geist } from 'next/font/google';
import { embedUrl, hashString, type SimContent, type SimClip } from '@/lib/demo-gen/content';
import GoLivePanel, { type GoLiveSession } from './go-live';

const geist = Geist({ subsets: ['latin'] });

export interface DemoSiteProps {
  slug: string;
  brandName: string;
  logoUrl: string | null;
  accentColor: string;
  template: 'DESTINATION' | 'FEED';
  genre: string;
}

interface ChatMsg {
  id: number;
  user: string;
  text: string;
  hue: number;
  self?: boolean;
}

function userHue(user: string): number {
  return hashString(user) % 360;
}

function ytThumb(id: string): string {
  return `https://img.youtube.com/vi/${id}/hqdefault.jpg`;
}

export default function BrandedDemo({ site, content }: { site: DemoSiteProps; content: SimContent }) {
  const [sdkLoaded, setSdkLoaded] = useState(false);
  const [liveSession, setLiveSession] = useState<GoLiveSession | null>(null);
  const [goLiveOpen, setGoLiveOpen] = useState(false);

  const handleLive = useCallback((s: GoLiveSession) => setLiveSession(s), []);
  const handleStopped = useCallback(() => setLiveSession(null), []);

  return (
    <div className={`${geist.className} min-h-screen bg-[#0e0e10] text-[#FAFAFA] tracking-tight flex flex-col`}>
      <Script src="https://web-broadcast.live-video.net/1.32.0/amazon-ivs-web-broadcast.js" onLoad={() => setSdkLoaded(true)} />

      <PreviewBanner brandName={site.brandName} accent={site.accentColor} />

      {site.template === 'DESTINATION' ? (
        <DestinationTemplate
          site={site}
          content={content}
          sdkLoaded={sdkLoaded}
          liveSession={liveSession}
          goLiveOpen={goLiveOpen}
          setGoLiveOpen={setGoLiveOpen}
          onLive={handleLive}
          onStopped={handleStopped}
        />
      ) : (
        <FeedTemplate
          site={site}
          content={content}
          sdkLoaded={sdkLoaded}
          liveSession={liveSession}
          goLiveOpen={goLiveOpen}
          setGoLiveOpen={setGoLiveOpen}
          onLive={handleLive}
          onStopped={handleStopped}
        />
      )}

      <FooterCta brandName={site.brandName} accent={site.accentColor} />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────
// Shared chrome
// ─────────────────────────────────────────────────────────────────

function PreviewBanner({ brandName, accent }: { brandName: string; accent: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <div className="flex items-center gap-3 px-4 py-2 text-xs border-b border-white/10 bg-[#18181B]">
      <span className="inline-flex items-center gap-1.5 text-white/50">
        <span className="size-1.5 rounded-full" style={{ background: accent }} />
        Simulated preview of <span className="text-white/80 font-medium">{brandName} Live</span> — generated by Substream in one click
      </span>
      <span className="ml-auto flex items-center gap-2">
        <button
          onClick={() => {
            navigator.clipboard.writeText(window.location.href).catch(() => {});
            setCopied(true);
            setTimeout(() => setCopied(false), 1500);
          }}
          className="rounded-full border border-white/15 px-3 py-1 text-white/60 hover:text-white hover:bg-white/5 transition-colors"
        >
          {copied ? 'Link copied!' : 'Share this demo'}
        </button>
        <Link href="/try" className="rounded-full px-3 py-1 font-medium text-white transition-opacity hover:opacity-85" style={{ background: accent }}>
          Build yours →
        </Link>
      </span>
    </div>
  );
}

function BrandMark({ site }: { site: DemoSiteProps }) {
  return (
    <span className="flex items-center gap-2.5 min-w-0">
      {site.logoUrl ? (
        <img src={site.logoUrl} alt={site.brandName} className="size-8 rounded-lg object-contain bg-white/10 shrink-0" />
      ) : (
        <span className="flex size-8 shrink-0 items-center justify-center rounded-lg text-sm font-bold text-white" style={{ background: site.accentColor }}>
          {site.brandName.charAt(0).toUpperCase()}
        </span>
      )}
      <span className="font-semibold truncate">{site.brandName}</span>
      <span className="rounded px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wide text-white shrink-0" style={{ background: site.accentColor }}>
        Live
      </span>
    </span>
  );
}

function FooterCta({ brandName, accent }: { brandName: string; accent: string }) {
  return (
    <footer className="border-t border-white/10 bg-[#18181B] px-6 py-10 text-center space-y-4 mt-auto">
      <h2 className="text-2xl font-medium tracking-tighter">
        This could be <span style={{ color: accent }}>{brandName}</span> next month.
      </h2>
      <p className="text-white/50 text-sm max-w-xl mx-auto leading-relaxed">
        Everything above — branded player, chat, clips, and the real live stream you just watched — runs on
        Substream&apos;s SDK and infrastructure. Integration is a few lines of code.
      </p>
      <div className="flex items-center justify-center gap-3 flex-wrap pt-1">
        <Link href="/demo" className="inline-flex h-10 items-center rounded-full px-5 text-sm font-semibold text-white transition-opacity hover:opacity-85" style={{ background: accent }}>
          See the SDK in action
        </Link>
        <Link href="/docs" className="inline-flex h-10 items-center rounded-full border border-white/15 px-5 text-sm font-medium text-white/80 hover:bg-white/5 transition-colors">
          Read the docs
        </Link>
      </div>
      <p className="text-xs text-white/25 pt-2">
        Powered by <Link href="/" className="underline hover:text-white/50">Substream</Link> — live streaming infrastructure for games
      </p>
    </footer>
  );
}

// ─────────────────────────────────────────────────────────────────
// Simulated chat
// ─────────────────────────────────────────────────────────────────

function useSimChat(content: SimContent, liveNow: boolean) {
  const [messages, setMessages] = useState<ChatMsg[]>([]);
  const idRef = useRef(0);

  const push = useCallback((user: string, text: string, self = false) => {
    idRef.current += 1;
    setMessages((prev) => [...prev.slice(-80), { id: idRef.current, user, text, hue: userHue(user), self }]);
  }, []);

  useEffect(() => {
    let timeout: ReturnType<typeof setTimeout>;
    const tick = () => {
      const user = content.chatUsers[Math.floor(Math.random() * content.chatUsers.length)];
      const pool = liveNow
        ? [...content.chatLines, 'yo someone just went LIVE', 'new streamer just dropped', 'welcome to the stream!', 'sub-second latency btw', 'this is running on WebRTC??']
        : content.chatLines;
      push(user, pool[Math.floor(Math.random() * pool.length)]);
      timeout = setTimeout(tick, 1200 + Math.random() * 2200);
    };
    timeout = setTimeout(tick, 600);
    return () => clearTimeout(timeout);
  }, [content, liveNow, push]);

  return { messages, push };
}

function ChatPanel({
  content,
  accent,
  brandName,
  liveNow,
}: {
  content: SimContent;
  accent: string;
  brandName: string;
  liveNow: boolean;
}) {
  const { messages, push } = useSimChat(content, liveNow);
  const [draft, setDraft] = useState('');
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight });
  }, [messages]);

  function send(e: React.FormEvent) {
    e.preventDefault();
    if (!draft.trim()) return;
    push('you', draft.trim(), true);
    setDraft('');
  }

  return (
    <div className="flex flex-col h-full min-h-0">
      <div className="px-4 py-3 border-b border-white/10 text-xs font-semibold uppercase tracking-wide text-white/50">
        {brandName} chat
      </div>
      <div ref={scrollRef} className="flex-1 overflow-y-auto px-4 py-3 space-y-2 text-sm min-h-0">
        {messages.map((m) => (
          <div key={m.id} className="leading-snug break-words">
            <span className="font-semibold" style={{ color: m.self ? accent : `hsl(${m.hue},70%,68%)` }}>
              {m.user}
            </span>
            <span className="text-white/70">: {m.text}</span>
          </div>
        ))}
      </div>
      <form onSubmit={send} className="p-3 border-t border-white/10 flex gap-2">
        <input
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          placeholder="Send a message"
          className="flex-1 rounded-lg border border-white/10 bg-white/[0.04] px-3 py-2 text-sm placeholder:text-white/25 focus:outline-none focus:border-white/25"
        />
        <button type="submit" className="rounded-lg px-3.5 py-2 text-sm font-semibold text-white transition-opacity hover:opacity-85" style={{ background: accent }}>
          Chat
        </button>
      </form>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────
// Viewer count that drifts like a live stream
// ─────────────────────────────────────────────────────────────────

function useDriftingCount(base: number) {
  const [count, setCount] = useState(base);
  useEffect(() => {
    setCount(base);
    const t = setInterval(() => {
      setCount((c) => Math.max(10, c + Math.floor(Math.random() * 41) - 18));
    }, 3000);
    return () => clearInterval(t);
  }, [base]);
  return count;
}

function fmtViewers(n: number): string {
  return n >= 1000 ? `${(n / 1000).toFixed(1)}k` : `${n}`;
}

// ─────────────────────────────────────────────────────────────────
// Template 1: Twitch-style destination
// ─────────────────────────────────────────────────────────────────

interface TemplateProps {
  site: DemoSiteProps;
  content: SimContent;
  sdkLoaded: boolean;
  liveSession: GoLiveSession | null;
  goLiveOpen: boolean;
  setGoLiveOpen: (open: boolean) => void;
  onLive: (s: GoLiveSession) => void;
  onStopped: () => void;
}

function DestinationTemplate({ site, content, sdkLoaded, liveSession, goLiveOpen, setGoLiveOpen, onLive, onStopped }: TemplateProps) {
  const accent = site.accentColor;
  const [selected, setSelected] = useState(0);
  const [clipModal, setClipModal] = useState<SimClip | null>(null);
  const channel = content.channels[selected];
  const viewers = useDriftingCount(channel.viewers);
  const watchingYou = useDriftingCount(12);

  const showingRealStream = liveSession !== null;

  return (
    <>
      {/* Site nav */}
      <nav className="flex items-center gap-4 px-5 py-3 border-b border-white/10 bg-[#18181B]">
        <BrandMark site={site} />
        <div className="hidden md:flex flex-1 max-w-sm mx-4">
          <div className="w-full rounded-full border border-white/10 bg-white/[0.04] px-4 py-1.5 text-sm text-white/30">Search streams…</div>
        </div>
        <button
          onClick={() => setGoLiveOpen(!goLiveOpen)}
          className="ml-auto inline-flex h-9 items-center gap-2 rounded-full px-4 text-sm font-semibold text-white transition-opacity hover:opacity-85 active:scale-95"
          style={{ background: goLiveOpen ? '#3f3f46' : accent }}
        >
          {goLiveOpen ? 'Close broadcast panel' : '⦿ Go live yourself'}
        </button>
      </nav>

      <div className="flex flex-1 min-h-0">
        {/* Channel sidebar */}
        <aside className="hidden lg:flex w-60 shrink-0 flex-col border-r border-white/10 bg-[#18181B]/60">
          <p className="px-4 pt-4 pb-2 text-xs font-semibold uppercase tracking-wide text-white/40">Live channels</p>
          <div className="flex-1 overflow-y-auto pb-4">
            {showingRealStream && (
              <ChannelRow
                streamer="You"
                title={`Live on ${site.brandName}`}
                viewers={watchingYou}
                hue={0}
                accent={accent}
                active
                isYou
                onClick={() => {}}
              />
            )}
            {content.channels.map((c, i) => (
              <ChannelRow
                key={c.streamer}
                streamer={c.streamer}
                title={c.title}
                viewers={i === selected ? viewers : c.viewers}
                hue={c.avatarHue}
                accent={accent}
                active={!showingRealStream && i === selected}
                onClick={() => setSelected(i)}
              />
            ))}
          </div>
        </aside>

        {/* Main column */}
        <main className="flex-1 min-w-0 flex flex-col">
          {/* Player */}
          <div className="relative bg-black aspect-video max-h-[62vh] w-full">
            {showingRealStream ? (
              <iframe
                key={liveSession.streamId}
                src={`/viewer/${liveSession.streamId}?auth=demo-viewer-token`}
                title="Your live stream"
                allow="autoplay; fullscreen"
                className="absolute inset-0 h-full w-full"
              />
            ) : (
              <iframe
                key={channel.videoId}
                src={embedUrl(channel.videoId)}
                title={channel.title}
                allow="autoplay; encrypted-media"
                className="absolute inset-0 h-full w-full pointer-events-none"
              />
            )}
            <span className="absolute top-3 left-3 inline-flex items-center gap-1.5 rounded px-2 py-0.5 text-[11px] font-bold text-white bg-red-600">
              LIVE
            </span>
            <span className="absolute top-3 right-3 rounded bg-black/70 px-2 py-0.5 text-[11px] font-semibold text-white/90">
              {showingRealStream ? fmtViewers(watchingYou) : fmtViewers(viewers)} watching
            </span>
          </div>

          {/* Stream meta */}
          <div className="flex items-center gap-3 px-5 py-4 border-b border-white/10">
            <Avatar name={showingRealStream ? 'You' : channel.streamer} hue={showingRealStream ? 0 : channel.avatarHue} accent={accent} isYou={showingRealStream} />
            <div className="min-w-0 flex-1">
              <p className="font-semibold truncate">{showingRealStream ? 'You' : channel.streamer}</p>
              <p className="text-sm text-white/50 truncate">
                {showingRealStream ? `Broadcasting live on ${site.brandName} — real WebRTC, sub-second latency` : channel.title}
              </p>
            </div>
            <button className="rounded-full px-4 py-1.5 text-sm font-semibold text-white transition-opacity hover:opacity-85" style={{ background: accent }}>
              Follow
            </button>
          </div>

          {/* Broadcast panel */}
          {goLiveOpen && (
            <div className="px-5 py-4 border-b border-white/10 bg-white/[0.02]">
              <p className="text-xs font-semibold uppercase tracking-wide text-white/50 mb-3">
                Your game — broadcasting into the player above
              </p>
              <GoLivePanel
                accent={accent}
                brandName={site.brandName}
                playerName="You"
                sdkLoaded={sdkLoaded}
                onLive={onLive}
                onStopped={onStopped}
              />
            </div>
          )}

          {/* Clips rail */}
          <div className="px-5 py-4">
            <div className="flex items-center gap-2 mb-3">
              <p className="text-sm font-semibold">Top clips</p>
              <span className="rounded-full border border-white/15 px-2 py-0.5 text-[10px] text-white/50 uppercase tracking-wide">
                auto-generated by AI
              </span>
            </div>
            <div className="flex gap-3 overflow-x-auto pb-2">
              {content.clips.map((clip) => (
                <button key={clip.title} onClick={() => setClipModal(clip)} className="w-48 shrink-0 text-left group">
                  <div className="relative rounded-lg overflow-hidden border border-white/10">
                    <img src={ytThumb(clip.videoId)} alt={clip.title} className="w-full aspect-video object-cover group-hover:scale-105 transition-transform duration-300" />
                    <span className="absolute bottom-1.5 right-1.5 rounded bg-black/80 px-1.5 py-0.5 text-[10px] font-semibold">{clip.duration}</span>
                    <span className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                      <span className="flex size-9 items-center justify-center rounded-full text-white" style={{ background: accent }}>▶</span>
                    </span>
                  </div>
                  <p className="mt-1.5 text-xs font-medium leading-snug line-clamp-2">{clip.title}</p>
                  <p className="text-[11px] text-white/40">{clip.streamer} · {clip.views} views</p>
                </button>
              ))}
            </div>
          </div>
        </main>

        {/* Chat */}
        <aside className="hidden md:flex w-72 xl:w-80 shrink-0 flex-col border-l border-white/10 bg-[#18181B]/60">
          <ChatPanel content={content} accent={accent} brandName={site.brandName} liveNow={showingRealStream} />
        </aside>
      </div>

      {clipModal && <ClipModal clip={clipModal} accent={accent} onClose={() => setClipModal(null)} />}
    </>
  );
}

function ChannelRow({
  streamer,
  title,
  viewers,
  hue,
  accent,
  active,
  isYou,
  onClick,
}: {
  streamer: string;
  title: string;
  viewers: number;
  hue: number;
  accent: string;
  active: boolean;
  isYou?: boolean;
  onClick: () => void;
}) {
  return (
    <button
      onClick={onClick}
      className={`w-full flex items-center gap-2.5 px-4 py-2.5 text-left transition-colors ${active ? 'bg-white/[0.06]' : 'hover:bg-white/[0.03]'}`}
    >
      <Avatar name={streamer} hue={hue} accent={accent} isYou={isYou} />
      <span className="min-w-0 flex-1">
        <span className="block text-sm font-medium truncate">{streamer}</span>
        <span className="block text-xs text-white/40 truncate">{title}</span>
      </span>
      <span className="flex items-center gap-1 text-xs text-white/50 shrink-0">
        <span className="size-1.5 rounded-full bg-red-500" />
        {fmtViewers(viewers)}
      </span>
    </button>
  );
}

function Avatar({ name, hue, accent, isYou }: { name: string; hue: number; accent: string; isYou?: boolean }) {
  return (
    <span
      className="flex size-8 shrink-0 items-center justify-center rounded-full text-xs font-bold text-white"
      style={{ background: isYou ? accent : `hsl(${hue},55%,45%)` }}
    >
      {name.charAt(0).toUpperCase()}
    </span>
  );
}

function ClipModal({ clip, accent, onClose }: { clip: SimClip; accent: string; onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4" onClick={onClose}>
      <div className="w-full max-w-2xl rounded-2xl border border-white/10 bg-[#18181B] overflow-hidden" onClick={(e) => e.stopPropagation()}>
        <div className="relative aspect-video bg-black">
          <iframe src={embedUrl(clip.videoId, false)} title={clip.title} allow="autoplay; encrypted-media" className="absolute inset-0 h-full w-full" />
        </div>
        <div className="px-5 py-4 flex items-center gap-3">
          <div className="min-w-0 flex-1">
            <p className="font-semibold truncate">{clip.title}</p>
            <p className="text-xs text-white/40 mt-0.5">
              {clip.streamer} · {clip.views} views · clipped automatically by
              <span className="font-medium" style={{ color: accent }}> Substream AI Highlights</span>
            </p>
          </div>
          <button onClick={onClose} className="rounded-full border border-white/15 px-4 py-1.5 text-sm text-white/70 hover:bg-white/5">
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────
// Template 2: social clips feed
// ─────────────────────────────────────────────────────────────────

function FeedTemplate({ site, content, sdkLoaded, liveSession, goLiveOpen, setGoLiveOpen, onLive, onStopped }: TemplateProps) {
  const accent = site.accentColor;
  const watchingYou = useDriftingCount(12);

  return (
    <>
      <nav className="flex items-center gap-4 px-5 py-3 border-b border-white/10 bg-[#18181B] sticky top-0 z-20">
        <BrandMark site={site} />
        <button
          onClick={() => setGoLiveOpen(!goLiveOpen)}
          className="ml-auto inline-flex h-9 items-center gap-2 rounded-full px-4 text-sm font-semibold text-white transition-opacity hover:opacity-85 active:scale-95"
          style={{ background: goLiveOpen ? '#3f3f46' : accent }}
        >
          {goLiveOpen ? 'Close broadcast panel' : '⦿ Go live'}
        </button>
      </nav>

      <main className="flex-1 w-full max-w-xl mx-auto px-4 py-6 space-y-4">
        {/* Go-live card (the real moment) */}
        {goLiveOpen && (
          <div className="rounded-2xl border p-4 space-y-4" style={{ borderColor: `${accent}66`, background: `${accent}0d` }}>
            <p className="text-sm font-semibold">Broadcast to the {site.brandName} community — for real</p>
            {liveSession && (
              <div className="relative rounded-xl overflow-hidden border border-white/10 bg-black aspect-video">
                <iframe
                  key={liveSession.streamId}
                  src={`/viewer/${liveSession.streamId}?auth=demo-viewer-token`}
                  title="Your live stream"
                  allow="autoplay; fullscreen"
                  className="absolute inset-0 h-full w-full"
                />
                <span className="absolute top-3 left-3 inline-flex items-center gap-1.5 rounded px-2 py-0.5 text-[11px] font-bold text-white bg-red-600">LIVE</span>
                <span className="absolute top-3 right-3 rounded bg-black/70 px-2 py-0.5 text-[11px] font-semibold">{fmtViewers(watchingYou)} watching</span>
              </div>
            )}
            <GoLivePanel
              accent={accent}
              brandName={site.brandName}
              playerName="You"
              sdkLoaded={sdkLoaded}
              onLive={onLive}
              onStopped={onStopped}
            />
          </div>
        )}

        {liveSession && (
          <FeedCard
            accent={accent}
            streamer="You"
            hue={0}
            isYou
            timestamp="now"
            caption={`Live right now on ${site.brandName} — real stream, sub-second latency`}
            media={
              <div className="relative rounded-xl overflow-hidden border border-white/10 bg-black aspect-video">
                <iframe
                  src={`/viewer/${liveSession.streamId}?auth=demo-viewer-token`}
                  title="Your live stream"
                  allow="autoplay; fullscreen"
                  className="absolute inset-0 h-full w-full"
                />
                <span className="absolute top-3 left-3 inline-flex items-center gap-1.5 rounded px-2 py-0.5 text-[11px] font-bold text-white bg-red-600">LIVE</span>
              </div>
            }
            likes={7}
            views="—"
          />
        )}

        {content.clips.map((clip, i) => (
          <ClipFeedCard key={clip.title} clip={clip} accent={accent} timestamp={`${(i + 1) * 2}h`} />
        ))}

        <div className="text-center py-6">
          <p className="text-sm text-white/40 mb-3">Clips like these are generated automatically from every stream.</p>
          <Link href="/try" className="inline-flex h-10 items-center rounded-full px-5 text-sm font-semibold text-white" style={{ background: accent }}>
            Build this for your community →
          </Link>
        </div>
      </main>
    </>
  );
}

function ClipFeedCard({ clip, accent, timestamp }: { clip: SimClip; accent: string; timestamp: string }) {
  const [playing, setPlaying] = useState(false);
  return (
    <FeedCard
      accent={accent}
      streamer={clip.streamer}
      hue={userHue(clip.streamer)}
      timestamp={timestamp}
      caption={clip.title}
      likes={clip.likes}
      views={clip.views}
      media={
        playing ? (
          <div className="relative rounded-xl overflow-hidden border border-white/10 bg-black aspect-video">
            <iframe src={embedUrl(clip.videoId, false)} title={clip.title} allow="autoplay; encrypted-media" className="absolute inset-0 h-full w-full" />
          </div>
        ) : (
          <button onClick={() => setPlaying(true)} className="relative block w-full rounded-xl overflow-hidden border border-white/10 group">
            <img src={ytThumb(clip.videoId)} alt={clip.title} className="w-full aspect-video object-cover" />
            <span className="absolute inset-0 flex items-center justify-center bg-black/20 group-hover:bg-black/10 transition-colors">
              <span className="flex size-12 items-center justify-center rounded-full text-white text-lg" style={{ background: accent }}>▶</span>
            </span>
            <span className="absolute bottom-2 right-2 rounded bg-black/80 px-1.5 py-0.5 text-[10px] font-semibold">{clip.duration}</span>
          </button>
        )
      }
    />
  );
}

function FeedCard({
  accent,
  streamer,
  hue,
  isYou,
  timestamp,
  caption,
  media,
  likes,
  views,
}: {
  accent: string;
  streamer: string;
  hue: number;
  isYou?: boolean;
  timestamp: string;
  caption: string;
  media: React.ReactNode;
  likes: number;
  views: string;
}) {
  const [liked, setLiked] = useState(false);
  const [reposted, setReposted] = useState(false);
  return (
    <article className="rounded-2xl border border-white/10 bg-[#18181B] p-4 space-y-3">
      <div className="flex items-center gap-2.5">
        <Avatar name={streamer} hue={hue} accent={accent} isYou={isYou} />
        <div className="min-w-0 flex-1">
          <p className="text-sm font-semibold truncate">{streamer}</p>
          <p className="text-xs text-white/35">{timestamp}</p>
        </div>
        {isYou && (
          <span className="inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold text-white bg-red-600">
            <span className="size-1.5 rounded-full bg-white animate-pulse" /> LIVE
          </span>
        )}
      </div>
      <p className="text-sm text-white/85 leading-snug">{caption}</p>
      {media}
      <div className="flex items-center gap-5 text-xs text-white/45 pt-0.5">
        <button onClick={() => setLiked(!liked)} className={`flex items-center gap-1.5 transition-colors ${liked ? '' : 'hover:text-white'}`} style={liked ? { color: accent } : undefined}>
          {liked ? '♥' : '♡'} {likes + (liked ? 1 : 0)}
        </button>
        <button onClick={() => setReposted(!reposted)} className={`flex items-center gap-1.5 transition-colors ${reposted ? 'text-green-400' : 'hover:text-white'}`}>
          ⇄ {12 + (reposted ? 1 : 0)}
        </button>
        <span className="flex items-center gap-1.5">💬 {Math.max(2, likes % 37)}</span>
        <span className="ml-auto">{views} views</span>
      </div>
    </article>
  );
}
