import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { prisma } from '@/lib/prisma';
import { buildSimContent } from '@/lib/demo-gen/content';
import BrandedDemo from './branded-demo';

export const dynamic = 'force-dynamic';

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const site = await prisma.demoSite.findUnique({ where: { slug } });
  if (!site) return { title: 'Demo not found' };
  return {
    title: `${site.brandName} Live — powered by Substream`,
    description: `A preview of ${site.brandName}'s own live streaming platform, generated by Substream.`,
  };
}

export default async function DemoSitePage({ params }: Props) {
  const { slug } = await params;
  const site = await prisma.demoSite.findUnique({ where: { slug } });
  if (!site) notFound();

  const content = buildSimContent(site.slug, site.genre);

  return (
    <BrandedDemo
      site={{
        slug: site.slug,
        brandName: site.brandName,
        logoUrl: site.logoUrl,
        accentColor: site.accentColor,
        template: site.template,
        genre: site.genre,
      }}
      content={content}
    />
  );
}
