#!/usr/bin/env bash
# Sync IVSBackend production env vars from Railway → Vercel.
#
# Prerequisites:
#   - railway CLI linked to extraordinary-curiosity / production
#   - vercel CLI linked to the target project (cd IVSBackend && vercel link)
#
# Usage:
#   ./scripts/vercel-prod-setup.sh              # push env to linked Vercel project
#   ./scripts/vercel-prod-setup.sh --export-only  # write import file only (for pinly dashboard)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EXPORT_ONLY=false
IMPORT_FILE="${REPO_ROOT}/IVSBackend/.env.production.vercel.import"

for arg in "$@"; do
  case "$arg" in
    --export-only) EXPORT_ONLY=true ;;
  esac
done

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "Missing required command: $1" >&2; exit 1; }
}

require_cmd railway
require_cmd python3

if [[ "$EXPORT_ONLY" == false ]]; then
  require_cmd vercel
fi

echo "Reading Railway production variables…"

SDK_JSON="$(cd "$REPO_ROOT" && railway variables --service substream-sdk --json)"
PG_JSON="$(cd "$REPO_ROOT" && railway variables --service Postgres --json)"

python3 - "$SDK_JSON" "$PG_JSON" "$IMPORT_FILE" "$EXPORT_ONLY" <<'PY'
import json, os, subprocess, sys

sdk = {k.strip(): v for k, v in json.loads(sys.argv[1]).items()}
pg = {k.strip(): v for k, v in json.loads(sys.argv[2]).items()}
import_file = sys.argv[3]
export_only = sys.argv[4] == "true"

database_url = pg.get("DATABASE_PUBLIC_URL") or pg.get("DATABASE_URL", "")
highlight_url = sdk.get("HIGHLIGHT_SERVICE_URL", "")

# Keys copied from Railway → Vercel (skip Railway-internal vars).
keys = [
    "AWS_ACCESS_KEY_ID",
    "AWS_REGION",
    "AWS_SECRET_ACCESS_KEY",
    "DEMO_ORG_CODE",
    "HIGHLIGHT_SERVICE_URL",
    "IVS_CHANNEL_ARN",
    "IVS_PLAYBACK_KEY_PAIR_ID",
    "IVS_PLAYBACK_PRIVATE_KEY",
    "IVS_RECORDING_CONFIG_ARN",
    "IVS_STAGE_ARN",
    "JWT_SECRET",
    "S3_RECORDING_BUCKET",
    "STREAM_KEY_ENCRYPTION_KEY",
]

lines = [
    "# Generated by scripts/vercel-prod-setup.sh — import in Vercel → Settings → Environment Variables",
    f"NODE_ENV=production",
    f"DATABASE_URL={database_url}",
]
for key in keys:
    val = sdk.get(key, "")
    if val:
        lines.append(f"{key}={val}")

if highlight_url:
    lines.append(f"NEXT_PUBLIC_HIGHLIGHT_SERVICE_URL={highlight_url}")

content = "\n".join(lines) + "\n"
with open(import_file, "w", encoding="utf-8") as f:
    f.write(content)

print(f"Wrote {import_file} ({len(lines)} vars)")

if export_only:
    sys.exit(0)

# Push each var to the linked Vercel project (Production).
os.chdir(os.path.join(os.path.dirname(import_file)))

def vercel_set(name: str, value: str, sensitive: bool = False) -> None:
    cmd = ["vercel", "env", "add", name, "production", "--force", "--yes"]
    if sensitive:
        cmd.insert(4, "--sensitive")
    if "\n" in value:
        subprocess.run(cmd, check=True, input=value.encode(), stdout=subprocess.DEVNULL)
    else:
        cmd.extend(["--value", value])
        subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL)

sensitive = {
    "DATABASE_URL", "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY",
    "IVS_PLAYBACK_PRIVATE_KEY", "JWT_SECRET", "STREAM_KEY_ENCRYPTION_KEY",
    "DEMO_ORG_CODE",
}

for line in lines:
    if line.startswith("#") or not line.strip():
        continue
    name, _, value = line.partition("=")
    vercel_set(name, value, name in sensitive)
    print(f"  ✓ {name}")

print("\nDone. Redeploy production in Vercel to pick up new env vars.")
PY

if [[ "$EXPORT_ONLY" == false ]]; then
  echo ""
  echo "Reminder: set Root Directory to IVSBackend in Vercel → Settings → General"
  echo "Build settings are in IVSBackend/vercel.json"
fi
